services:
  sender:
    image: alpine
    command: "ash -c 'sleep 7; for i in $(seq 1 5); do wget -q -S -O - http://echo:8888 2>&1; done'"
  echo:
    image: alpine
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888
    command: "nc -p 8888 -s 0.0.0.0 -v -lk -e /bin/echo -ne 'HTTP/1.1 200 OK\n\nSuccessful response\n\n'"
  listener:
    command: ash -c "
          ./brian
          "
#           ash config/config-iptables.sh
#           && clean_rules
    volumes:
      - ./docker_debug/:/config
    build:
      context: .
      dockerfile: cmd/DevDockerfile
    network_mode: "service:echo"
    cap_add:
      - NET_ADMIN
